function k(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}}function l(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):{next:k(b)}}var m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,p="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,d){b!=Array.prototype&&b!=Object.prototype&&(b[a]=d.value)};
function q(b,a){if(a){var d=m;b=b.split(".");for(var e=0;e<b.length-1;e++){var g=b[e];g in d||(d[g]={});d=d[g]}b=b[b.length-1];e=d[b];a=a(e);a!=e&&null!=a&&p(d,b,{configurable:!0,writable:!0,value:a})}}
q("Promise",function(b){function a(a){this.b=0;this.g=void 0;this.a=[];var c=this.c();try{a(c.resolve,c.reject)}catch(f){c.reject(f)}}function d(){this.a=null}function e(c){return c instanceof a?c:new a(function(a){a(c)})}if(b)return b;d.prototype.b=function(a){if(null==this.a){this.a=[];var c=this;this.c(function(){c.g()})}this.a.push(a)};var g=m.setTimeout;d.prototype.c=function(a){g(a,0)};d.prototype.g=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var f=
a[b];a[b]=null;try{f()}catch(h){this.f(h)}}}this.a=null};d.prototype.f=function(a){this.c(function(){throw a;})};a.prototype.c=function(){function a(a){return function(c){f||(f=!0,a.call(b,c))}}var b=this,f=!1;return{resolve:a(this.o),reject:a(this.f)}};a.prototype.o=function(b){if(b===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.s(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.m(b):this.i(b)}};
a.prototype.m=function(a){var b=void 0;try{b=a.then}catch(f){this.f(f);return}"function"==typeof b?this.u(b,a):this.i(a)};a.prototype.f=function(a){this.j(2,a)};a.prototype.i=function(a){this.j(1,a)};a.prototype.j=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.g=b;this.l()};a.prototype.l=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)x.b(this.a[a]);this.a=null}};var x=new d;a.prototype.s=function(a){var b=this.c();
a.h(b.resolve,b.reject)};a.prototype.u=function(a,b){var c=this.c();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};a.prototype.then=function(b,d){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(H){n(H)}}:b}var e,n,G=new a(function(a,b){e=a;n=b});this.h(c(b,e),c(d,n));return G};a.prototype.catch=function(a){return this.then(void 0,a)};a.prototype.h=function(a,b){function c(){switch(e.b){case 1:a(e.g);break;case 2:b(e.g);break;default:throw Error("Unexpected state: "+
e.b);}}var e=this;null==this.a?x.b(c):this.a.push(c)};a.resolve=e;a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(a,c){for(var d=l(b),f=d.next();!f.done;f=d.next())e(f.value).h(a,c)})};a.all=function(b){var c=l(b),d=c.next();return d.done?e([]):new a(function(a,b){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,e(d.value).h(f(g.length-1),b),d=c.next();while(!d.done)})};return a});
var r=document.getElementById("bookmarks"),t=window.localStorage,u=document.querySelector("#notification-wrapper"),v=document.querySelector("form#bookmark_form"),w=document.getElementById("bookmark-input__name"),y=document.getElementById("bookmark-input__url"),z=[],A=1,B=1;
function C(b,a,d){var e=document.importNode(document.querySelector("#bookmark").content,!0);e.querySelector(".item").dataset.id=b;e.querySelector(".item__link h3").textContent=a;e.querySelector(".item__link").href=d;e.querySelector(".item__link--delete").addEventListener("click",D);z.length>20*A?A+=1:20<=r.childElementCount||r.appendChild(e)}
function D(b){var a=E(),d=b.target.parentNode;r.removeChild(d);a=a.filter(function(a){return a.id!==d.dataset.id});t.setItem("bookmarks",JSON.stringify(a));F("Deleted bookmark!")}function I(){u.querySelectorAll(".notification").forEach(function(b){u.removeChild(b)})}function F(b){var a=document.importNode(document.getElementById("notification").content,!0);a.querySelector(".notification__message").textContent=b;I();u.appendChild(a)}
function J(){var b=E();b&&(b=b.slice(20*(B-1),40*B),r.querySelectorAll(".item").forEach(function(a){r.removeChild(a)}),b.forEach(function(a){C(a.id,a.name,a.url)}),document.getElementById("page_number").textContent=B)}function E(){var b=t.getItem("bookmarks");return b?JSON.parse(b):null}
v.addEventListener("submit",function(b){b.preventDefault();b=y.value.trim();w.value.trim()&&b?/^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i.test(b)?(b={id:"_"+Math.random().toString(36).substr(2,9),name:w.value,url:y.value},z.push(b),t.setItem("bookmarks",JSON.stringify(z)),F("Added bookmark successfully!"),C(b.id,b.name,b.url),v.reset()):F("Cannot connect to the URL provided"):F("Please provide both name and url")});
document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".pagination__button").forEach(function(b){b.addEventListener("click",function(a){a.preventDefault();a=b.dataset.direction;"left"===a&&1<B?(--B,J()):"right"===a&&B<A&&(B+=1,J())})});J()});
